server:
  port: 8761
  
spring:
  application:
    name: eureka-service
  profiles: 
    active:
    - dev
    
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    wait-time-in-ms-when-sync-empty: 0